"""Initial database schema

Revision ID: 6095ae1f021e
Revises: 
Create Date: 2026-09-04 10:47:34.130197
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6095ae1f021e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_site', sa.String(), nullable=False),
    sa.Column('active_personnel', sa.Integer(), nullable=False),
    sa.Column('compliance_score', sa.Integer(), nullable=False),
    sa.Column('expiring_certifications', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('msha_audit_date', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Compliant', 'Flagged', 'Review Required')", name='ck_contractor_status'),
    sa.CheckConstraint('active_personnel >= 0', name='ck_contractor_active_personnel'),
    sa.CheckConstraint('compliance_score >= 0 AND compliance_score <= 100', name='ck_contractor_compliance_score'),
    sa.CheckConstraint('expiring_certifications >= 0', name='ck_contractor_expiring_certifications'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contractors_status', 'contractors', ['status'], unique=False)
    op.create_table('mines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('mine_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('primary_contractor', sa.String(), nullable=False),
    sa.Column('coordinates', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ai_recommendation', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Active (At Risk)', 'Operational', 'Maintenance Required', 'Inspection Scheduled')", name='ck_mine_status'),
    sa.CheckConstraint('risk_score >= 0 AND risk_score <= 100', name='ck_mine_risk_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_mines_mine_type', 'mines', ['mine_type'], unique=False)
    op.create_index('ix_mines_region', 'mines', ['region'], unique=False)
    op.create_index('ix_mines_status', 'mines', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MINE_MANAGER', 'INSPECTOR', 'COMPLIANCE_OFFICER', 'FIELD_OFFICER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('mine', sa.String(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('deadline', sa.String(), nullable=False),
    sa.Column('is_ai_prediction', sa.Boolean(), nullable=False),
    sa.Column('prob_score', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('assigned_to', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("severity IN ('Critical', 'High', 'Medium', 'Resolved')", name='ck_alert_severity'),
    sa.CheckConstraint("status IN ('Unacknowledged', 'Investigating', 'Resolved', 'In Progress')", name='ck_alert_status'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_mine', 'alerts', ['mine'], unique=False)
    op.create_index('ix_alerts_severity', 'alerts', ['severity'], unique=False)
    op.create_index('ix_alerts_status', 'alerts', ['status'], unique=False)
    op.create_table('compliance_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('requirement', sa.String(), nullable=False),
    sa.Column('mine', sa.String(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('due_date', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('responsible_officer', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ai_insight', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('Safety', 'Environmental', 'Equipment', 'Ventilation')", name='ck_compliance_category'),
    sa.CheckConstraint("risk_level IN ('High', 'Medium', 'Low')", name='ck_compliance_risk_level'),
    sa.CheckConstraint("status IN ('Overdue', 'Pending', 'Completed')", name='ck_compliance_status'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('ix_compliance_category', 'compliance_requirements', ['category'], unique=False)
    op.create_index('ix_compliance_mine', 'compliance_requirements', ['mine'], unique=False)
    op.create_index('ix_compliance_status', 'compliance_requirements', ['status'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('sector', sa.String(), nullable=False),
    sa.Column('mine_id', sa.UUID(), nullable=True),
    sa.Column('gps_text', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('Active', 'Resolved', 'Dismissed')", name='ck_inspection_status'),
    sa.ForeignKeyConstraint(['mine_id'], ['mines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inspections_sector', 'inspections', ['sector'], unique=False)
    op.create_index('ix_inspections_status', 'inspections', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inspections_status', table_name='inspections')
    op.drop_index('ix_inspections_sector', table_name='inspections')
    op.drop_table('inspections')
    op.drop_index('ix_compliance_status', table_name='compliance_requirements')
    op.drop_index('ix_compliance_mine', table_name='compliance_requirements')
    op.drop_index('ix_compliance_category', table_name='compliance_requirements')
    op.drop_table('compliance_requirements')
    op.drop_index('ix_alerts_status', table_name='alerts')
    op.drop_index('ix_alerts_severity', table_name='alerts')
    op.drop_index('ix_alerts_mine', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_mines_status', table_name='mines')
    op.drop_index('ix_mines_region', table_name='mines')
    op.drop_index('ix_mines_mine_type', table_name='mines')
    op.drop_table('mines')
    op.drop_index('ix_contractors_status', table_name='contractors')
    op.drop_table('contractors')
    # ### end Alembic commands ###
